---
title: "Vitamin D: case (T1 D) control (Healthy) list"
author: "Debojyoti Das"
date: "2025-05-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
pacman::p_load(
  haven,        # File import
  here,         # File locator
  sjlabelled,
  janitor,      
  data.table,   
  comprehenr
)
```

```{r}
data_root <- "/Users/debda22/OneDrive - Linköpings universitet/Linkoping_projects/ABIS_RAW_DATA_SPSS/"
```

auto-immune list
```{r}
autoimm <- haven::read_sav(paste0(data_root,"L40_corrected.sav"))
autoimm <- autoimm %>% 
  as.data.frame() %>%
  dplyr::filter(AutoimmDisease == 1) %>%
  dplyr::pull(ABISnr)
attributes(autoimm) <- NULL
autoimm <- sapply(autoimm, function(x) as.character(x))
```

```{r}
E10 <- readxl::read_xlsx(paste0(data_root,"vitamin_d/Debojyoti_cordblood.xlsx"))
cases <- E10$`ABISnr T1D(Cord Blood)`
cases <- cases[!is.na(cases)]
```


```{r}
vitamin_d <- readxl::read_xlsx(paste0(data_root,"vitamin_d/Vitamin_D_16_2023_ABIS.xlsx"))
vitamin_d <- vitamin_d %>% as.data.frame()
head(vitamin_d,3)
```

```{r}
column_names <- c("LID_nr_rekv_nr_MBK", "ABISnr", "LIDnr", "DBP", "25OHD", "boks_1_del_1_av_2_4_4_24")
vitamin_d <- vitamin_d[-c(1,2),-6]
names(vitamin_d) <-column_names
head(vitamin_d,4)
```
